spring:
  application:
    name: secretary
  main:
    banner-mode: off
  shell:
    interactive:
      enabled: true
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
          options:
            model: gemini-2.0-flash
logging:
  level:
    root: info
    org.tianea: info
