spring:
  application:
    name: secretary
  main:
    banner-mode: off
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5435/secretary
    username: secretary
    password: secretary
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
          options:
            model: gemini-2.0-flash
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
secretary:
  chat:
    memory:
      window-size: 20
logging:
  level:
    root: info
    org.tianea: info
