package org.tianea.secretary.telegram.latex

/**
 * LaTeX 토큰 → 유니코드 매핑 테이블 모음.
 *
 * [UnicodeMathRenderer]가 참조하는 순수 데이터. LaTeX2e math, amsmath, Comprehensive LaTeX Symbol List에서 LLM이
 * 흔히 출력하는 범위를 추렸다. 완전한 LaTeX 심볼 집합은 아니며, 미등록 토큰은 렌더러가 원본 LaTeX로 폴백한다.
 */
internal object LatexSymbols {
    /** 인자 없는 `\command` → 유니코드 문자. 그리스 문자·연산자·관계자·화살표·집합/논리·기타. */
    val COMMAND_MAP: Map<String, String> =
        mapOf(
            "alpha" to "α",
            "beta" to "β",
            "gamma" to "γ",
            "delta" to "δ",
            "epsilon" to "ε",
            "varepsilon" to "ε",
            "zeta" to "ζ",
            "eta" to "η",
            "theta" to "θ",
            "vartheta" to "ϑ",
            "iota" to "ι",
            "kappa" to "κ",
            "lambda" to "λ",
            "mu" to "μ",
            "nu" to "ν",
            "xi" to "ξ",
            "omicron" to "ο",
            "pi" to "π",
            "varpi" to "ϖ",
            "rho" to "ρ",
            "varrho" to "ϱ",
            "sigma" to "σ",
            "varsigma" to "ς",
            "tau" to "τ",
            "upsilon" to "υ",
            "phi" to "φ",
            "varphi" to "ϕ",
            "chi" to "χ",
            "psi" to "ψ",
            "omega" to "ω",
            "Alpha" to "Α",
            "Beta" to "Β",
            "Gamma" to "Γ",
            "Delta" to "Δ",
            "Epsilon" to "Ε",
            "Zeta" to "Ζ",
            "Eta" to "Η",
            "Theta" to "Θ",
            "Iota" to "Ι",
            "Kappa" to "Κ",
            "Lambda" to "Λ",
            "Mu" to "Μ",
            "Nu" to "Ν",
            "Xi" to "Ξ",
            "Omicron" to "Ο",
            "Pi" to "Π",
            "Rho" to "Ρ",
            "Sigma" to "Σ",
            "Tau" to "Τ",
            "Upsilon" to "Υ",
            "Phi" to "Φ",
            "Chi" to "Χ",
            "Psi" to "Ψ",
            "Omega" to "Ω",
            "pm" to "±",
            "mp" to "∓",
            "times" to "×",
            "div" to "÷",
            "cdot" to "·",
            "ast" to "∗",
            "star" to "⋆",
            "circ" to "∘",
            "bullet" to "•",
            "oplus" to "⊕",
            "otimes" to "⊗",
            "ominus" to "⊖",
            "oslash" to "⊘",
            "odot" to "⊙",
            "leq" to "≤",
            "le" to "≤",
            "geq" to "≥",
            "ge" to "≥",
            "neq" to "≠",
            "ne" to "≠",
            "approx" to "≈",
            "equiv" to "≡",
            "sim" to "∼",
            "simeq" to "≃",
            "cong" to "≅",
            "propto" to "∝",
            "ll" to "≪",
            "gg" to "≫",
            "doteq" to "≐",
            "asymp" to "≍",
            "prec" to "≺",
            "succ" to "≻",
            "preceq" to "⪯",
            "succeq" to "⪰",
            "to" to "→",
            "gets" to "←",
            "leftarrow" to "←",
            "rightarrow" to "→",
            "leftrightarrow" to "↔",
            "Rightarrow" to "⇒",
            "Leftarrow" to "⇐",
            "Leftrightarrow" to "⇔",
            "implies" to "⇒",
            "iff" to "⇔",
            "mapsto" to "↦",
            "longrightarrow" to "⟶",
            "longleftarrow" to "⟵",
            "longleftrightarrow" to "⟷",
            "uparrow" to "↑",
            "downarrow" to "↓",
            "updownarrow" to "↕",
            "nearrow" to "↗",
            "searrow" to "↘",
            "swarrow" to "↙",
            "nwarrow" to "↖",
            "hookrightarrow" to "↪",
            "hookleftarrow" to "↩",
            "infty" to "∞",
            "partial" to "∂",
            "nabla" to "∇",
            "forall" to "∀",
            "exists" to "∃",
            "nexists" to "∄",
            "in" to "∈",
            "notin" to "∉",
            "ni" to "∋",
            "subset" to "⊂",
            "supset" to "⊃",
            "subseteq" to "⊆",
            "supseteq" to "⊇",
            "subsetneq" to "⊊",
            "supsetneq" to "⊋",
            "cup" to "∪",
            "cap" to "∩",
            "bigcup" to "⋃",
            "bigcap" to "⋂",
            "setminus" to "∖",
            "emptyset" to "∅",
            "varnothing" to "∅",
            "land" to "∧",
            "wedge" to "∧",
            "lor" to "∨",
            "vee" to "∨",
            "lnot" to "¬",
            "neg" to "¬",
            "top" to "⊤",
            "bot" to "⊥",
            "perp" to "⊥",
            "parallel" to "∥",
            "nparallel" to "∦",
            "angle" to "∠",
            "measuredangle" to "∡",
            "triangle" to "△",
            "square" to "□",
            "diamond" to "⋄",
            "vdash" to "⊢",
            "dashv" to "⊣",
            "models" to "⊨",
            "therefore" to "∴",
            "because" to "∵",
            "mid" to "∣",
            "nmid" to "∤",
            "sum" to "Σ",
            "prod" to "∏",
            "coprod" to "∐",
            "int" to "∫",
            "iint" to "∬",
            "iiint" to "∭",
            "oint" to "∮",
            "bigoplus" to "⨁",
            "bigotimes" to "⨂",
            "bigwedge" to "⋀",
            "bigvee" to "⋁",
            "sqrt" to "√",
            "surd" to "√",
            "cdots" to "⋯",
            "ldots" to "…",
            "dots" to "…",
            "vdots" to "⋮",
            "ddots" to "⋱",
            "hbar" to "ℏ",
            "ell" to "ℓ",
            "Re" to "ℜ",
            "Im" to "ℑ",
            "wp" to "℘",
            "aleph" to "ℵ",
            "beth" to "ℶ",
            "gimel" to "ℷ",
            "daleth" to "ℸ",
            "prime" to "′",
            "backprime" to "‵",
            "degree" to "°",
            "circ_degree" to "°",
            "pm_minus" to "∓",
            "dagger" to "†",
            "ddagger" to "‡",
            "S" to "§",
            "P" to "¶",
            "copyright" to "©",
            "pounds" to "£",
            "checkmark" to "✓",
            "clubsuit" to "♣",
            "diamondsuit" to "♦",
            "heartsuit" to "♥",
            "spadesuit" to "♠",
            "flat" to "♭",
            "natural" to "♮",
            "sharp" to "♯",
            "quad" to "  ",
            "qquad" to "    ",
            "," to " ",
            ";" to " ",
            ":" to " ",
            "!" to "",
            " " to " ",
            "lbrace" to "{",
            "rbrace" to "}",
            "{" to "{",
            "}" to "}",
            "%" to "%",
            "&" to "&",
            "#" to "#",
            "_" to "_",
            "lim" to "lim",
            "sin" to "sin",
            "cos" to "cos",
            "tan" to "tan",
            "cot" to "cot",
            "sec" to "sec",
            "csc" to "csc",
            "log" to "log",
            "ln" to "ln",
            "exp" to "exp",
            "min" to "min",
            "max" to "max",
            "gcd" to "gcd",
            "deg" to "deg",
            "det" to "det",
            "dim" to "dim",
            "ker" to "ker",
            "arg" to "arg",
            "sinh" to "sinh",
            "cosh" to "cosh",
            "tanh" to "tanh",
            "arcsin" to "arcsin",
            "arccos" to "arccos",
            "arctan" to "arctan",
            "sup" to "sup",
            "inf" to "inf",
        )

    /** `\mathbb{X}` 단일 대문자 → 블랙보드 볼드. */
    val MATHBB_MAP: Map<Char, String> =
        mapOf(
            'A' to "𝔸",
            'B' to "𝔹",
            'C' to "ℂ",
            'D' to "𝔻",
            'E' to "𝔼",
            'F' to "𝔽",
            'G' to "𝔾",
            'H' to "ℍ",
            'I' to "𝕀",
            'J' to "𝕁",
            'K' to "𝕂",
            'L' to "𝕃",
            'M' to "𝕄",
            'N' to "ℕ",
            'O' to "𝕆",
            'P' to "ℙ",
            'Q' to "ℚ",
            'R' to "ℝ",
            'S' to "𝕊",
            'T' to "𝕋",
            'U' to "𝕌",
            'V' to "𝕍",
            'W' to "𝕎",
            'X' to "𝕏",
            'Y' to "𝕐",
            'Z' to "ℤ",
        )

    /** `\mathcal{X}` 단일 대문자 → 캘리그래픽. */
    val MATHCAL_MAP: Map<Char, String> =
        mapOf(
            'A' to "𝒜",
            'B' to "ℬ",
            'C' to "𝒞",
            'D' to "𝒟",
            'E' to "ℰ",
            'F' to "ℱ",
            'G' to "𝒢",
            'H' to "ℋ",
            'I' to "ℐ",
            'J' to "𝒥",
            'K' to "𝒦",
            'L' to "ℒ",
            'M' to "ℳ",
            'N' to "𝒩",
            'O' to "𝒪",
            'P' to "𝒫",
            'Q' to "𝒬",
            'R' to "ℛ",
            'S' to "𝒮",
            'T' to "𝒯",
            'U' to "𝒰",
            'V' to "𝒱",
            'W' to "𝒲",
            'X' to "𝒳",
            'Y' to "𝒴",
            'Z' to "𝒵",
        )

    /** `\mathfrak{X}` 단일 글자 → 프락투어. */
    val MATHFRAK_MAP: Map<Char, String> =
        mapOf(
            'A' to "𝔄",
            'B' to "𝔅",
            'C' to "ℭ",
            'D' to "𝔇",
            'E' to "𝔈",
            'F' to "𝔉",
            'G' to "𝔊",
            'H' to "ℌ",
            'I' to "ℑ",
            'J' to "𝔍",
            'K' to "𝔎",
            'L' to "𝔏",
            'M' to "𝔐",
            'N' to "𝔑",
            'O' to "𝔒",
            'P' to "𝔓",
            'Q' to "𝔔",
            'R' to "ℜ",
            'S' to "𝔖",
            'T' to "𝔗",
            'U' to "𝔘",
            'V' to "𝔙",
            'W' to "𝔚",
            'X' to "𝔛",
            'Y' to "𝔜",
            'Z' to "ℨ",
        )

    /** 위첨자로 변환 가능한 글자. 한 글자라도 없으면 [UnicodeMathRenderer]가 폴백한다. */
    val SUPERSCRIPT_MAP: Map<Char, Char> =
        mapOf(
            '0' to '⁰',
            '1' to '¹',
            '2' to '²',
            '3' to '³',
            '4' to '⁴',
            '5' to '⁵',
            '6' to '⁶',
            '7' to '⁷',
            '8' to '⁸',
            '9' to '⁹',
            '+' to '⁺',
            '-' to '⁻',
            '=' to '⁼',
            '(' to '⁽',
            ')' to '⁾',
            'a' to 'ᵃ',
            'b' to 'ᵇ',
            'c' to 'ᶜ',
            'd' to 'ᵈ',
            'e' to 'ᵉ',
            'f' to 'ᶠ',
            'g' to 'ᵍ',
            'h' to 'ʰ',
            'i' to 'ⁱ',
            'j' to 'ʲ',
            'k' to 'ᵏ',
            'l' to 'ˡ',
            'm' to 'ᵐ',
            'n' to 'ⁿ',
            'o' to 'ᵒ',
            'p' to 'ᵖ',
            'r' to 'ʳ',
            's' to 'ˢ',
            't' to 'ᵗ',
            'u' to 'ᵘ',
            'v' to 'ᵛ',
            'w' to 'ʷ',
            'x' to 'ˣ',
            'y' to 'ʸ',
            'z' to 'ᶻ',
        )

    /** 아래첨자로 변환 가능한 글자. 한 글자라도 없으면 [UnicodeMathRenderer]가 폴백한다. */
    val SUBSCRIPT_MAP: Map<Char, Char> =
        mapOf(
            '0' to '₀',
            '1' to '₁',
            '2' to '₂',
            '3' to '₃',
            '4' to '₄',
            '5' to '₅',
            '6' to '₆',
            '7' to '₇',
            '8' to '₈',
            '9' to '₉',
            '+' to '₊',
            '-' to '₋',
            '=' to '₌',
            '(' to '₍',
            ')' to '₎',
            'a' to 'ₐ',
            'e' to 'ₑ',
            'h' to 'ₕ',
            'i' to 'ᵢ',
            'j' to 'ⱼ',
            'k' to 'ₖ',
            'l' to 'ₗ',
            'm' to 'ₘ',
            'n' to 'ₙ',
            'o' to 'ₒ',
            'p' to 'ₚ',
            'r' to 'ᵣ',
            's' to 'ₛ',
            't' to 'ₜ',
            'u' to 'ᵤ',
            'v' to 'ᵥ',
            'x' to 'ₓ',
        )

    /** 액센트 명령 → 결합 분음 기호(combining diacritical mark). */
    val ACCENT_MAP: Map<String, Char> =
        mapOf(
            "dot" to '̇',
            "ddot" to '̈',
            "dddot" to '⃛',
            "hat" to '̂',
            "widehat" to '̂',
            "bar" to '̄',
            "overline" to '̄',
            "vec" to '⃗',
            "tilde" to '̃',
            "widetilde" to '̃',
            "check" to '̌',
            "breve" to '̆',
            "acute" to '́',
            "grave" to '̀',
            "mathring" to '̊',
        )

    /** `_`/`^`를 상하한으로 흡수하는 큰 연산자 명령. */
    val BIG_OPERATORS: Set<String> =
        setOf(
            "sum",
            "prod",
            "coprod",
            "int",
            "iint",
            "iiint",
            "oint",
            "bigcup",
            "bigcap",
            "bigoplus",
            "bigotimes",
            "bigwedge",
            "bigvee",
            "lim",
        )

    /** 인자 하나를 받아 내용만 평문 노출하는 폰트/텍스트 래퍼 명령. */
    val FONT_COMMANDS: Set<String> =
        setOf(
            "text",
            "textrm",
            "textbf",
            "textit",
            "textsf",
            "texttt",
            "mathrm",
            "mathbf",
            "mathit",
            "mathsf",
            "mathtt",
            "mathbb",
            "mathcal",
            "mathfrak",
            "mathnormal",
            "boldsymbol",
            "operatorname",
            "mathscr",
        )

    /** 평탄화 대상 환경 이름. 미등록 환경도 파서는 제네릭 처리한다. */
    val ENVIRONMENT_NAMES: Set<String> =
        setOf(
            "matrix",
            "pmatrix",
            "bmatrix",
            "Bmatrix",
            "vmatrix",
            "Vmatrix",
            "smallmatrix",
            "array",
            "cases",
            "align",
            "align*",
            "aligned",
            "aligned*",
            "gather",
            "gather*",
            "gathered",
            "equation",
            "equation*",
            "split",
            "multline",
        )

    /** `matrix` 계열 — 블록을 대괄호로 감싼다. */
    val BRACKETED_ENVIRONMENTS: Set<String> =
        setOf(
            "matrix",
            "pmatrix",
            "bmatrix",
            "Bmatrix",
            "vmatrix",
            "Vmatrix",
            "smallmatrix",
            "array",
        )

    /** `\left`/`\right` 뒤에 오는 구분자 명령 → 유니코드 괄호. 평문 구분자(`( ) [ ]` 등)는 그대로 통과. */
    val DELIMITER_MAP: Map<String, String> =
        mapOf(
            "langle" to "⟨",
            "rangle" to "⟩",
            "lvert" to "|",
            "rvert" to "|",
            "lVert" to "‖",
            "rVert" to "‖",
            "vert" to "|",
            "Vert" to "‖",
            "lfloor" to "⌊",
            "rfloor" to "⌋",
            "lceil" to "⌈",
            "rceil" to "⌉",
            "lbrace" to "{",
            "rbrace" to "}",
            "lbrack" to "[",
            "rbrack" to "]",
            "backslash" to "\\",
        )
}
